apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: demo-app
          image: ghcr.io/shyaminda/demo-app:c37f7fc
          ports:
            - name: http
              containerPort: 3000

  strategy:
    canary:
      stableService: demo-app-stable
      canaryService: demo-app-canary
      steps:
        - setWeight: 100