apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: demo-app
          image: ghcr.io/shyaminda/demo-app:6a06e97
          ports:
            - containerPort: 3000
          env:
            - name: SLOW_MODE
              value: "true"

  strategy:
    canary:
      stableService: demo-app-stable
      canaryService: demo-app-canary
      steps:
        - setWeight: 10
        - pause: {}